[tool.poetry]
name = "hcp-vault-secrets-client"
version = "0.0.1"
description = "Hashi-Corp Vault Secrets Client"
authors = [
    "Schipper <107776081+TheSchipper@users.noreply.github.com>",
]


[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"