name: CI

on:
  workflow_dispatch:
  push:
    branches: [main, initial]
  pull_request:
    branches: [main, initial]

jobs:
  workflow:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          python-version: ${{ matrix.python-version }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -e .
          pip install --no-cache-dir tox==4.0.0 tox-gh-actions==2.7.0

      - name: Tests with Tox
        run: tox
