# Simple workflow for deploying static content to GitHub Pages
name: Deploy Sphinx Documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "initial"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Sphinx
        run: |
          pip install -U sphinx

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Build docs
        run: |
          export PYTHONPATH=$PWD/src:$PYTHONPATH
          touch src/__init__.py
          sphinx-apidoc -o $PWD/docs/source $PWD
          sphinx-build $PWD/docs/source $PWD/docs/build

      - name: Fix directory titles
        run: |
          sed -i 's/src package/src/g' $PWD/docs/source/src.rst
          sed -i 's/===========/===/g' $PWD/docs/source/src.rst
          sed -i 's/tests package/tests/g' $PWD/docs/source/tests.rst
          sed -i 's/=============/=====/g' $PWD/docs/source/tests.rst
          cat $PWD/docs/source/src.rst
          cat $PWD/docs/source/tests.rst

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs/build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
